name: ExplosiveSwearing
main: org.dyndns.fishery.ExplosiveSwearing.ExplosiveSwearing
version: 0.5
description: This plugin blows up anyone who swears.
author: pbfy0
softdepend: [WorldGuard, Vault]
commands:
    exswear:
        description: All commands for ExplosiveSwearing
        permission: explosiveswearing.reload
        usage: /exswear reload - Reload the plugin
permissions:
    explosiveswearing.*:
        description: Everything for ExplosiveSwearing
        default: false
        children:
            explosiveswearing.reload: true
            explosiveswearing.exempt: true
    explosiveswearing.reload:
        description: Reload ExplosiveSwearing
        default: false
    explosiveswearing.exempt:
        description: Be exempted from exploding from swearing
        default: false